# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_ScaleSpikeSlab_rcpp_hello_world`)
}

#' @export
fcprd <- function(X) {
    .Call(`_ScaleSpikeSlab_fcprd`, X)
}

#' @export
cpp_prod <- function(X, Y) {
    .Call(`_ScaleSpikeSlab_cpp_prod`, X, Y)
}

#' @export
cpp_mat_vec_prod <- function(X, y) {
    .Call(`_ScaleSpikeSlab_cpp_mat_vec_prod`, X, y)
}

